In [62]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2

In [63]:
def custom_blur_demo(image):
    kernel = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]], np.float32) #锐化
    dst = cv.filter2D(image, -1, kernel=kernel)
    return dst

In [66]:
test_img = cv2.imread('dataset/test.png')
test_img = custom_blur_demo(test_img)
hsv = cv2.cvtColor(test_img, cv2.COLOR_BGR2HSV)
lower_blue = np.array([100, 50, 50])
upper_blue = np.array([110, 255, 255])
mask = cv2.inRange(hsv, lower_blue, upper_blue)
H, S, V = cv2.split(hsv)
print("h:{}, s:{}, v:{}".format(H, S, V))
res = cv2.bitwise_and(test_img, test_img, mask=mask)
print(test_img.shape)
cv2.imshow('original', test_img)
cv2.imshow('extract', res)
cv2.waitKey(0)
cv2.destroyAllWindows()

h:[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [67 67 67 ... 51 49 60]
 [60 60 60 ... 46 48 60]
 [28 28 28 ... 40 40 47]], s:[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [164 100 115 ... 188 255 255]
 [ 85  67  75 ... 255 255 255]
 [105 115  96 ... 142 153 255]], v:[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [ 14  23  20 ...  23  27  11]
 [ 15  19  17 ...  29  24  11]
 [ 34  31  37 ...  43  35  23]]
(586, 586, 3)


In [ ]:
test_img = cv2.imread('dataset/test.png')
